# Generated by Django 5.1.4 on 2026-01-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fridges/')),
            ],
        ),
        migrations.CreateModel(
            name='RefrigeratorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1_temp', models.FloatField()),
                ('sensor2_temp', models.FloatField()),
                ('is_out_of_range', models.BooleanField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('air_temp', models.FloatField(blank=True, null=True)),
                ('event_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_records', to='fr1.fridge')),
            ],
        ),
    ]
