# Generated by Django 5.1.4 on 2026-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigeratordata',
            name='door_open_duration_sec',
        ),
        migrations.RemoveField(
            model_name='refrigeratordata',
            name='power_lost',
        ),
        migrations.AlterField(
            model_name='refrigeratordata',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
